resources:
    - name: git-repo
      type: git
      source:
          uri: https://github.com/varesa/packer-vsphere
          branch: master

    - name: container-image
      type: docker-image
      source:
          repository: registry.esav.fi/tools/packer
          username: ((autom_username))
          password: ((autom_password))

jobs:
    - name: Build and publish image
      public: true
      serial: true
      plan:
          - get: git-repo
          - put: container-image
            params:
                build: git-repo
                dockerfile: git-repo/container/Dockerfile
